# 端口
server:
  port: 7070

spring:
  datasource:
    name: demo
    # 数据库url
    url: jdbc:mysql://localhost:3306/springboot-vue?serverTimezone=CTT&characterEncoding=utf-8&useSSL=false
    # 数据库账号
    username: root  
    # 数据库密码
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    # 数据连接池类型
    type: com.alibaba.druid.pool.DruidDataSource
    # druid数据连接池配置
    druid:
      # 数据连接池初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 验证连接有效与否的SQL，不同的数据配置不同
      validation-query: SELECT 1 FROM DUAL
      # 执行validationQuery检测连接是否有效
      test-while-idle: true
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      max-pool-prepared-statement-per-connection-size: 20
      # 监控统计用的filter:stat
      filters: stat
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 配置监控服务器
      stat-view-servlet:
        # druid 1.1.0以上版本enbled必须为true
        enabled: true
        # 浏览输入http://localhost:(springboot端口)/druid即可访问druid后台管理
        login-username: admin
        login-password: 123456
        reset-enable: false
        url-pattern: /druid/*

  # redis配置
  redis:
    # redis服务器地址
    host: localhost
    # redis服务器端口
    port: 6379
    # redis服务器连接密码（默认为空）
    password: 
    # 连接超时（毫秒）
    timeout: 1000
    jedis:
      pool:
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 30000
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0

# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.example.springboottemplate.entity
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      # field-strategy: NOT_EMPTY
      #数据库类型
      # db-type: MYSQL
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: false
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: false
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
